# syntax = docker/dockerfile:1

ARG NODE_VERSION=18.20.7

FROM node:${NODE_VERSION}-slim as base

ENV NODE_ENV=development

WORKDIR /app

# Build
FROM base as build

COPY .env.dev .env .
COPY --link package.json package-lock.json .
RUN npm install

# Run
FROM base

COPY --from=build /app/node_modules /app/node_modules

# Start the application
CMD ["npm", "run", "dev", "--", "--port", "5173"]