ARG NODE_VERSION=18.20.7

FROM node:${NODE_VERSION}-slim

ENV NODE_ENV=development
ENV PATH=/app/node_modules/.bin:$PATH

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5190

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5190"]