services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-adhp
    image: adhp_backend
    ports:
      - 8301:8301
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT:-5439}
      DATABASE_HOST: ${DATABASE_HOST_DOCKER:-db_adhp}
      CODE_HANDLER_API_URL: ${CODE_HANDLER_API_URL}
      CODE_HANDLER_KEY: ${CODE_HANDLER_KEY}
      SALTDB: ${SALTDB}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      MY_SIGNING_KEY: ${MY_SIGNING_KEY}
    networks:
      - adhp

  frontend-adhp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-adhp
    image: adhp_frontend
    ports:
      - "5190:5190"
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    depends_on:
      - backend
    networks:
      - adhp

  code_handler:
    build:
      context: ./code_handler
      dockerfile: Dockerfile
    container_name: code-handler-adhp
    image: adhp_code_handler
    ports:
      - 8302:8302
    environment:
      CODE_HANDLER_KEY: ${CODE_HANDLER_KEY}
      CODE_HANDLER_REMOVE_FILES: ${CODE_HANDLER_REMOVE_FILES}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    volumes:
      - codes:/codes
    networks:
      - adhp

volumes:
  codes:
    driver: local

networks:
  adhp:
    external: true
