services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    image: tcc_backend
    ports:
      - 8080:8080
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_HOST: ${DATABASE_HOST:-db_tcc}
      CODE_HANDLER_API_URL: ${CODE_HANDLER_API_URL}
      CODE_HANDLER_KEY: ${CODE_HANDLER_KEY}
      SALTDB: ${SALTDB}
    depends_on:
      - db_tcc
      - pgadmin
    networks:
      - tcc_unesc

  frontend-tcc:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-tcc
    image: tcc_frontend
    ports:
      - "5173:5173"
      - "24678:24678"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - tcc_unesc

  code_handler:
    build: 
      context: ./code_handler
      dockerfile: Dockerfile.dev
    container_name: code_handler
    image: tcc_code_handler
    ports:
      - 8082:8082
    environment:
      CODE_HANDLER_KEY: ${CODE_HANDLER_KEY}
      CODE_HANDLER_REMOVE_FILES: ${CODE_HANDLER_REMOVE_FILES}
    volumes:
      - codes:/codes
    networks:
      - tcc_unesc

  db_tcc:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_tcc:/var/lib/postgresql/data
    networks:
      - tcc_unesc

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db_tcc
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8081:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - tcc_unesc

  nginx-tcc:
    container_name: nginx-tcc
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: tcc_nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tcc_unesc

volumes:
  db_tcc:
    driver: local
  pgadmin:
    driver: local
  codes:
    driver: local
  node_modules:
    # driver: local

networks:
  tcc_unesc:
    external: true