services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-adhp
    image: adhp_backend
    ports:
      - 8301:8301
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # porta/host da rede interna do docker (5439 é só o mapeamento no host)
      DATABASE_PORT: 5432
      DATABASE_HOST: db_adhp
      CODE_HANDLER_API_URL: http://code_handler:8302
      CODE_HANDLER_KEY: ${CODE_HANDLER_KEY}
      SALTDB: ${SALTDB}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      MY_SIGNING_KEY: ${MY_SIGNING_KEY}
    depends_on:
      - db_adhp
      - pgadmin
    networks:
      - adhp

  frontend-adhp:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-adhp
    image: adhp_frontend
    ports:
      - "5190:5190"
      - "24678:24678"
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - adhp

  code_handler:
    build:
      context: ./code_handler
      dockerfile: Dockerfile.dev
    container_name: code-handler-adhp
    image: adhp_code_handler
    ports:
      - 8302:8302
    environment:
      CODE_HANDLER_KEY: ${CODE_HANDLER_KEY}
      CODE_HANDLER_REMOVE_FILES: ${CODE_HANDLER_REMOVE_FILES}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    volumes:
      - codes:/codes
    networks:
      - adhp

  db_adhp:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_adhp:/var/lib/postgresql/data
    networks:
      - adhp

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-adhp
    restart: unless-stopped
    depends_on:
      - db_adhp
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8381:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - adhp

volumes:
  db_adhp:
    driver: local
  pgadmin:
    driver: local
  codes:
    driver: local

networks:
  adhp:
    external: true
