version: '3.8'

services:
  backend:
    image: ghcr.io/alfuveam/adhp/backend:latest
    container_name: backend-adhp
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      CODE_HANDLER_API_URL: ${CODE_HANDLER_API_URL}
      CODE_HANDLER_KEY: ${CODE_HANDLER_KEY}
      SALTDB: ${SALTDB}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    ports:
      - "8301:8301"

  frontend-adhp:
    image: ghcr.io/alfuveam/adhp/frontend:latest
    container_name: frontend-adhp
    ports:
      - "5190:5190"

  code_handler:
    image: ghcr.io/alfuveam/adhp/code_handler:latest
    container_name: code-handler-adhp
    environment:
      CODE_HANDLER_KEY: ${CODE_HANDLER_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    ports:
      - "8302:8302"
