FROM golang:1.23.4-alpine

RUN apk add --no-cache make git

# Install Air for hot reloading
RUN go install github.com/air-verse/air@v1.61.7

WORKDIR /app

# Copy go.mod and go.sum files first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

EXPOSE 8301

CMD ["air"]
